version: '3.7'
services:
      postgres:
            image: postgres
            container_name: app_db
            restart: unless-stopped
            environment:
                  POSTGRES_USER: "starter_kit"
                  POSTGRES_PASSWORD: "qwerty"
                  POSTGRES_DB: test
            volumes:
                  - postgres_data:/var/lib/postgresql/data/
            networks:
                  - backend
            
      api:
            build: 
                  context: .
                  dockerfile: Dockerfile
            container_name: api
            command: gunicorn --bind 0.0.0.0:5000 app:app
            ports:
                  - "5000:5000"
            environment:
                  POSTGRES_HOST: postgres
                  POSTGRES_USERNAME: "starter_kit"
                  POSTGRES_PASSWORD: "qwerty"
            volumes:
                  - appdata:/var/www/
            depends_on: 
                  - postgres
            networks:
                  - backend            

networks:
      backend:
            driver: bridge
volumes:
      appdata:
            driver: local
      postgres_data:
            driver: local